import PptxGenJS from 'pptxgenjs';

export const createTemplate = async () => {
  const pptx = new PptxGenJS();
  const slide = pptx.addSlide();
  
  // Set slide background
  slide.background = { fill: 'FFFFFF' };
  
  // Add title placeholder with NO formatting constraints
  slide.addText('{{BOARD_NAME}}', {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.8
  });
  
  // Add subtitle placeholder with NO formatting constraints
  slide.addText('{{CARD_COUNT}} cards • {{COLUMN_COUNT}} columns', {
    x: 0.5,
    y: 1.3,
    w: 9,
    h: 0.4
  });
  
  // Add logo/branding area (shape only)
  slide.addShape(pptx.ShapeType.rect, {
    x: 8.5,
    y: 0.3,
    w: 1,
    h: 0.6,
    fill: { color: 'E8F4FD' },
    line: { color: '3498DB', width: 1 }
  });
  
  slide.addText('LOGO', {
    x: 8.5,
    y: 0.45,
    w: 1,
    h: 0.3
  });
  
  // Add header for table section with NO formatting constraints
  slide.addText('Project Status Overview', {
    x: 0.5,
    y: 2,
    w: 9,
    h: 0.4
  });
  
  // Add table placeholder with MINIMAL formatting
  const tableData: any[][] = [
    ['Card', 'Last Activity', '{{DYNAMIC_COLUMNS}}'],
    ['{{DYNAMIC_ROWS}}', '', '']
  ];
  
  // Basic table with no special formatting
  slide.addTable(tableData, {
    x: 0.5,
    y: 2.5,
    w: 9,
    rowH: 0.6
  });
  
  // Add footer area (shape only)
  slide.addShape(pptx.ShapeType.rect, {
    x: 0.5,
    y: 6.8,
    w: 9,
    h: 0.7,
    fill: { color: 'F8F9FA' },
    line: { color: 'E9ECEF', width: 1 }
  });
  
  slide.addText('Exported on {{EXPORT_DATE}}', {
    x: 1,
    y: 7,
    w: 4,
    h: 0.3
  });
  
  slide.addText('Generated by Trello Swimlane Viewer', {
    x: 5.5,
    y: 7,
    w: 3.5,
    h: 0.3
  });
  
  // Save template
  await pptx.writeFile({ fileName: 'swimlane_template.pptx' });
  console.log('Template created successfully');
};

// Call this function to generate the template file
// You can run this in the browser console: 
// import('./utils/createTemplate').then(m => m.createTemplate())