import PptxGenJS from 'pptxgenjs';

export const createTemplate = async () => {
  const pptx = new PptxGenJS();
  const slide = pptx.addSlide();
  
  // Set slide background
  slide.background = { fill: 'FFFFFF' };
  
  // Add title placeholder - using minimal formatting for easy editing
  slide.addText('{{BOARD_NAME}}', {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.8,
    fontSize: 28,
    bold: true,
    align: 'center'
  });
  
  // Add subtitle placeholder - using minimal formatting for easy editing
  slide.addText('{{CARD_COUNT}} cards • {{COLUMN_COUNT}} columns', {
    x: 0.5,
    y: 1.3,
    w: 9,
    h: 0.4,
    fontSize: 14,
    align: 'center'
  });
  
  // Add logo/branding area (placeholder)
  slide.addShape(pptx.ShapeType.rect, {
    x: 8.5,
    y: 0.3,
    w: 1,
    h: 0.6,
    fill: { color: 'E8F4FD' },
    line: { color: '3498DB', width: 1 }
  });
  
  slide.addText('LOGO', {
    x: 8.5,
    y: 0.45,
    w: 1,
    h: 0.3,
    fontSize: 10,
    align: 'center'
  });
  
  // Add header for table section - using minimal formatting for easy editing
  slide.addText('Project Status Overview', {
    x: 0.5,
    y: 2,
    w: 9,
    h: 0.4,
    fontSize: 16,
    bold: true
  });
  
  // Add table placeholder - using minimal formatting for maximum editability
  const tableData: any[][] = [
    [
      { text: 'Card', options: { bold: true } },
      { text: 'Last Activity', options: { bold: true } },
      { text: '{{DYNAMIC_COLUMNS}}', options: { bold: true } }
    ],
    [
      { text: '{{DYNAMIC_ROWS}}' }
    ]
  ];
  
  // Note: This template table will be completely replaced with dynamic data during export
  slide.addTable(tableData, {
    x: 0.5,
    y: 2.5,
    w: 9,
    fontSize: 10,
    border: { pt: 1, color: 'CCCCCC' },
    rowH: 0.6,
    margin: 0.05
  });
  
  // Add footer area
  slide.addShape(pptx.ShapeType.rect, {
    x: 0.5,
    y: 6.8,
    w: 9,
    h: 0.7,
    fill: { color: 'F8F9FA' },
    line: { color: 'E9ECEF', width: 1 }
  });
  
  slide.addText('Exported on {{EXPORT_DATE}}', {
    x: 1,
    y: 7,
    w: 4,
    h: 0.3,
    fontSize: 10
  });
  
  slide.addText('Generated by Trello Swimlane Viewer', {
    x: 5.5,
    y: 7,
    w: 3.5,
    h: 0.3,
    fontSize: 10,
    align: 'right'
  });
  
  // Save template
  await pptx.writeFile({ fileName: 'swimlane_template.pptx' });
  console.log('Template created successfully');
};

// Call this function to generate the template file
// You can run this in the browser console: 
// import('./utils/createTemplate').then(m => m.createTemplate())