import PptxGenJS from 'pptxgenjs';

export const createTemplate = async () => {
  const pptx = new PptxGenJS();
  const slide = pptx.addSlide();
  
  // Set slide background
  slide.background = { fill: 'FFFFFF' };
  
  // Add title placeholder
  slide.addText('{{BOARD_NAME}}', {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.8,
    fontSize: 28,
    bold: true,
    color: '2C3E50',
    align: 'center',
    fontFace: 'Calibri'
  });
  
  // Add subtitle placeholder
  slide.addText('{{CARD_COUNT}} cards • {{COLUMN_COUNT}} columns', {
    x: 0.5,
    y: 1.3,
    w: 9,
    h: 0.4,
    fontSize: 14,
    color: '7F8C8D',
    align: 'center',
    fontFace: 'Calibri'
  });
  
  // Add logo/branding area (placeholder)
  slide.addShape(pptx.ShapeType.rect, {
    x: 8.5,
    y: 0.3,
    w: 1,
    h: 0.6,
    fill: { color: 'E8F4FD' },
    line: { color: '3498DB', width: 1 }
  });
  
  slide.addText('LOGO', {
    x: 8.5,
    y: 0.45,
    w: 1,
    h: 0.3,
    fontSize: 10,
    color: '3498DB',
    align: 'center',
    fontFace: 'Calibri'
  });
  
  // Add header for table section
  slide.addText('Project Status Overview', {
    x: 0.5,
    y: 2,
    w: 9,
    h: 0.4,
    fontSize: 16,
    bold: true,
    color: '2C3E50',
    fontFace: 'Calibri'
  });
  
  // Add table placeholder with sample data and styling
  const tableData: any[][] = [
    [
      { text: 'Card Name', options: { bold: true, fill: '3498DB', color: 'FFFFFF', fontFace: 'Calibri' } },
      { text: 'Current Status', options: { bold: true, fill: '3498DB', color: 'FFFFFF', fontFace: 'Calibri' } },
      { text: 'Progress', options: { bold: true, fill: '3498DB', color: 'FFFFFF', fontFace: 'Calibri' } },
      { text: 'Labels', options: { bold: true, fill: '3498DB', color: 'FFFFFF', fontFace: 'Calibri' } }
    ],
    [
      { text: '{{SAMPLE_CARD}}', options: { fontFace: 'Calibri' } },
      { text: '{{SAMPLE_STATUS}}', options: { fontFace: 'Calibri' } },
      { text: '{{SAMPLE_PROGRESS}}', options: { fontFace: 'Calibri' } },
      { text: '{{SAMPLE_LABELS}}', options: { fontFace: 'Calibri' } }
    ]
  ];
  
  slide.addTable(tableData, {
    x: 0.5,
    y: 2.5,
    w: 9,
    fontSize: 11,
    border: { pt: 1, color: 'BDC3C7' },
    rowH: 0.5,
    margin: 0.1
  });
  
  // Add footer area
  slide.addShape(pptx.ShapeType.rect, {
    x: 0.5,
    y: 6.8,
    w: 9,
    h: 0.7,
    fill: { color: 'F8F9FA' },
    line: { color: 'E9ECEF', width: 1 }
  });
  
  slide.addText('Exported on {{EXPORT_DATE}}', {
    x: 1,
    y: 7,
    w: 4,
    h: 0.3,
    fontSize: 10,
    color: '6C757D',
    fontFace: 'Calibri'
  });
  
  slide.addText('Generated by Trello Swimlane Viewer', {
    x: 5.5,
    y: 7,
    w: 3.5,
    h: 0.3,
    fontSize: 10,
    color: '6C757D',
    align: 'right',
    fontFace: 'Calibri'
  });
  
  // Save template
  await pptx.writeFile({ fileName: 'swimlane_template.pptx' });
  console.log('Template created successfully');
};